### ISSUE TITLE
"Out of resource" when trying to mine movable folders

### ISSUE THREAD

**Issue by Supernsixty4** [Jimmy-Z/bfCL#4]
Can anyone help me out with this part? Im trying to install a custom firmware on my 3ds. Im at the Seedminer part where i need to type these two commands for the movable files to pop up

py -3 seedminer_launcher3.py update-db
py -3 seedminer_launcher3.py gpu

But it keeps showing "out of resource" which i am guessing my gpu isn't strong enough to gather the movable files. Can anyone give any advice to resolve this issue? 

Here's the full "text" on the windowspowershell

Old3DS msed - this can happen on a New3DS
LFCS      : 0x6632e2c
msed3 est : 0x146f9e2
Error est : 3930
ID0 hash 0: c7934b018b7a0a392a1e46ac5db68b7a
Hash total: 1
movable_part2.sed generation success
bfcl msky 2c2e63060000000000000000e2f94601 c7934b018b7a0a392a1e46ac5db68b7a 00000000
selected device GeForce 840M on platform NVIDIA CUDA
0.004 seconds for OpenCL compiling
local work size: 1024
ocl_assert: ocl_brute.c, function ocl_brute_msky, line 383
        clEnqueueReadBuffer(command_queue, mem_out, CL_TRUE, 0, sizeof(cl_uint), &out, 0, NULL, NULL)
error: out of resources

**Comment by Jimmy-Z** [comment]
see #3
